name: deploy git page
on:
  push:
    branches:
      - master
  workflow_dispatch:
      
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          mkdir -p build
          rm -r ./.github/
          rm .gitignore
          sed -i 's/<base href="\/">/<base href="\/vtuber\/">/g' *.html
          shopt -s extglob
          cp -r !(build) ./build/
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.publish }}
          folder: build
          repository-name: fysh711426/fysh711426.github.io
          branch: master
          git-config-name: fysh711426
          git-config-email: fysh711426@gmail.com
          target-folder: vtuber
          commit-message: auto-commit
          force: false
          clean: false
          single-commit: true
